# Generated by Django 3.1.6 on 2021-02-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.IntegerField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('game_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
