# Generated by Django 3.1.6 on 2021-02-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='The Legend of Zelda: Breath of the Wild', max_length=100, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('in_stock', models.IntegerField()),
                ('platform', models.SlugField(default='Nintendo Switch')),
                ('game_type', models.CharField(default='ACT', max_length=100)),
            ],
        ),
    ]
